//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFileManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Globals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Globals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyFileManager.Globals", typeof(Globals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information on licensing and using Easy File Manager can be viewed at https://github.com/rafcolson/EasyFileManager. Issues can be reported on https://github.com/rafcolson/EasyFileManager/issues. Releases can be downloaded at https://github.com/rafcolson/EasyFileManager/releases..
        /// </summary>
        public static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area info.
        /// </summary>
        public static string AreaInfo {
            get {
                return ResourceManager.GetString("AreaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area info from Easy metadata.
        /// </summary>
        public static string AreaInfoFromEasyMetadata {
            get {
                return ResourceManager.GetString("AreaInfoFromEasyMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup folder does not exist. No changes made..
        /// </summary>
        public static string BackupFolderDoesNotExist {
            get {
                return ResourceManager.GetString("BackupFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera manufacturer.
        /// </summary>
        public static string CameraManufacturer {
            get {
                return ResourceManager.GetString("CameraManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera model.
        /// </summary>
        public static string CameraModel {
            get {
                return ResourceManager.GetString("CameraModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed.
        /// </summary>
        public static string Compressed {
            get {
                return ResourceManager.GetString("Compressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Contents {
            get {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates.
        /// </summary>
        public static string Coordinates {
            get {
                return ResourceManager.GetString("Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy | Move.
        /// </summary>
        public static string CopyMove {
            get {
                return ResourceManager.GetString("CopyMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom dictionary.
        /// </summary>
        public static string CustomDict {
            get {
                return ResourceManager.GetString("CustomDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom metadata.
        /// </summary>
        public static string CustomMetadata {
            get {
                return ResourceManager.GetString("CustomMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        public static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date (custom).
        /// </summary>
        public static string DateCustomize {
            get {
                return ResourceManager.GetString("DateCustomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateDefault {
            get {
                return ResourceManager.GetString("DateDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date earliest.
        /// </summary>
        public static string DateEarliest {
            get {
                return ResourceManager.GetString("DateEarliest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date encoded.
        /// </summary>
        public static string DateEncoded {
            get {
                return ResourceManager.GetString("DateEncoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date from Easy metadata.
        /// </summary>
        public static string DateFromEasyMetadata {
            get {
                return ResourceManager.GetString("DateFromEasyMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date from parent folder name.
        /// </summary>
        public static string DateFromFolderName {
            get {
                return ResourceManager.GetString("DateFromFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date (metadata).
        /// </summary>
        public static string DateMetadata {
            get {
                return ResourceManager.GetString("DateMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date modified.
        /// </summary>
        public static string DateModified {
            get {
                return ResourceManager.GetString("DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date taken.
        /// </summary>
        public static string DateTaken {
            get {
                return ResourceManager.GetString("DateTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date taken or encoded.
        /// </summary>
        public static string DateTakenOrEncoded {
            get {
                return ResourceManager.GetString("DateTakenOrEncoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day created.
        /// </summary>
        public static string DayCreated {
            get {
                return ResourceManager.GetString("DayCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day earliest.
        /// </summary>
        public static string DayEarliest {
            get {
                return ResourceManager.GetString("DayEarliest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day from Easy metadata.
        /// </summary>
        public static string DayFromEasyMetadata {
            get {
                return ResourceManager.GetString("DayFromEasyMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day taken or encoded.
        /// </summary>
        public static string DayTakenOrEncoded {
            get {
                return ResourceManager.GetString("DayTakenOrEncoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All duplicates will be deleted permanently. Continue?.
        /// </summary>
        public static string DeleteAllDuplicates {
            get {
                return ResourceManager.GetString("DeleteAllDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates of &apos;{0}&apos; will be deleted permanently. Continue?.
        /// </summary>
        public static string DeleteDuplicates {
            get {
                return ResourceManager.GetString("DeleteDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy metadata will be deleted. Continue?.
        /// </summary>
        public static string DeleteEasyMetadata {
            get {
                return ResourceManager.GetString("DeleteEasyMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete empty folders.
        /// </summary>
        public static string DeleteEmptyFolders {
            get {
                return ResourceManager.GetString("DeleteEmptyFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates.
        /// </summary>
        public static string DuplicatesDefault {
            get {
                return ResourceManager.GetString("DuplicatesDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates (delete).
        /// </summary>
        public static string DuplicatesDelete {
            get {
                return ResourceManager.GetString("DuplicatesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates destination folder does not exist. No changes made..
        /// </summary>
        public static string DuplicatesFolderDoesNotExist {
            get {
                return ResourceManager.GetString("DuplicatesFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates (move).
        /// </summary>
        public static string DuplicatesMove {
            get {
                return ResourceManager.GetString("DuplicatesMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy metadata.
        /// </summary>
        public static string EasyMetadata {
            get {
                return ResourceManager.GetString("EasyMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy, Shell or video metadata.
        /// </summary>
        public static string EasyShellOrVideoMetadata {
            get {
                return ResourceManager.GetString("EasyShellOrVideoMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit comparison profile.
        /// </summary>
        public static string EditComparisonProfile {
            get {
                return ResourceManager.GetString("EditComparisonProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Easy metadata.
        /// </summary>
        public static string EditEasyMetadata {
            get {
                return ResourceManager.GetString("EditEasyMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit filter.
        /// </summary>
        public static string EditFilter {
            get {
                return ResourceManager.GetString("EditFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit GPS.
        /// </summary>
        public static string EditGPS {
            get {
                return ResourceManager.GetString("EditGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit keywords.
        /// </summary>
        public static string EditKeywords {
            get {
                return ResourceManager.GetString("EditKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit subfolders.
        /// </summary>
        public static string EditSubfolders {
            get {
                return ResourceManager.GetString("EditSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        public static string EndsWith {
            get {
                return ResourceManager.GetString("EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore....
        /// </summary>
        public static string Explore {
            get {
                return ResourceManager.GetString("Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra large thumbnail.
        /// </summary>
        public static string ExtraLargeThumbnail {
            get {
                return ResourceManager.GetString("ExtraLargeThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension.
        /// </summary>
        public static string FileExtension {
            get {
                return ResourceManager.GetString("FileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type text.
        /// </summary>
        public static string FileTypeText {
            get {
                return ResourceManager.GetString("FileTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; already exists..
        /// </summary>
        public static string FormatAlreadyExists {
            get {
                return ResourceManager.GetString("FormatAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game media.
        /// </summary>
        public static string GameMedia {
            get {
                return ResourceManager.GetString("GameMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates.
        /// </summary>
        public static string Geocoords {
            get {
                return ResourceManager.GetString("Geocoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords (add).
        /// </summary>
        public static string KeywordsAdd {
            get {
                return ResourceManager.GetString("KeywordsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string KeywordsDefault {
            get {
                return ResourceManager.GetString("KeywordsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords (replace).
        /// </summary>
        public static string KeywordsReplace {
            get {
                return ResourceManager.GetString("KeywordsReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large thumbnail.
        /// </summary>
        public static string LargeThumbnail {
            get {
                return ResourceManager.GetString("LargeThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium thumbnail.
        /// </summary>
        public static string MediumThumbnail {
            get {
                return ResourceManager.GetString("MediumThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t ask again..
        /// </summary>
        public static string MessageCheckDialogText {
            get {
                return ResourceManager.GetString("MessageCheckDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month created.
        /// </summary>
        public static string MonthCreated {
            get {
                return ResourceManager.GetString("MonthCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month earliest.
        /// </summary>
        public static string MonthEarliest {
            get {
                return ResourceManager.GetString("MonthEarliest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month from Easy metadata.
        /// </summary>
        public static string MonthFromEasyMetadata {
            get {
                return ResourceManager.GetString("MonthFromEasyMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month taken or encoded.
        /// </summary>
        public static string MonthTakenOrEncoded {
            get {
                return ResourceManager.GetString("MonthTakenOrEncoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next folder.
        /// </summary>
        public static string NextFolder {
            get {
                return ResourceManager.GetString("NextFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One level up.
        /// </summary>
        public static string OneLevelUp {
            get {
                return ResourceManager.GetString("OneLevelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy metadata will be overwritten. Continue?.
        /// </summary>
        public static string OverwriteEasyMetadata {
            get {
                return ResourceManager.GetString("OverwriteEasyMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous folder.
        /// </summary>
        public static string PreviousFolder {
            get {
                return ResourceManager.GetString("PreviousFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw name.
        /// </summary>
        public static string RawName {
            get {
                return ResourceManager.GetString("RawName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string ReplaceNormal {
            get {
                return ResourceManager.GetString("ReplaceNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace (regex).
        /// </summary>
        public static string ReplaceRegex {
            get {
                return ResourceManager.GetString("ReplaceRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select backup folder.
        /// </summary>
        public static string SelectBackupFolder {
            get {
                return ResourceManager.GetString("SelectBackupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select duplicates destination folder.
        /// </summary>
        public static string SelectDuplicatesFolder {
            get {
                return ResourceManager.GetString("SelectDuplicatesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select top folder.
        /// </summary>
        public static string SelectTopFolder {
            get {
                return ResourceManager.GetString("SelectTopFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell properties.
        /// </summary>
        public static string ShellProperties {
            get {
                return ResourceManager.GetString("ShellProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show comparison dialog.
        /// </summary>
        public static string ShowComparisonDialog {
            get {
                return ResourceManager.GetString("ShowComparisonDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down system....
        /// </summary>
        public static string ShutingDown {
            get {
                return ResourceManager.GetString("ShutingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small thumbnail.
        /// </summary>
        public static string SmallThumbnail {
            get {
                return ResourceManager.GetString("SmallThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with.
        /// </summary>
        public static string StartsWith {
            get {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All duplicates will be stored in destination folder. Continue?.
        /// </summary>
        public static string StoreAllDuplicates {
            get {
                return ResourceManager.GetString("StoreAllDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates of &apos;{0}&apos; will be stored in destination folder. Continue?.
        /// </summary>
        public static string StoreDuplicates {
            get {
                return ResourceManager.GetString("StoreDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbolic link.
        /// </summary>
        public static string SymbolicLink {
            get {
                return ResourceManager.GetString("SymbolicLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top folder does not exist. No changes made..
        /// </summary>
        public static string TopFolderDoesNotExist {
            get {
                return ResourceManager.GetString("TopFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        public static string Unspecified {
            get {
                return ResourceManager.GetString("Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video metadata.
        /// </summary>
        public static string VideoMetadata {
            get {
                return ResourceManager.GetString("VideoMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write date created.
        /// </summary>
        public static string WriteDateCreated {
            get {
                return ResourceManager.GetString("WriteDateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write date Easy metadata.
        /// </summary>
        public static string WriteDateEasyMetadata {
            get {
                return ResourceManager.GetString("WriteDateEasyMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write date modified.
        /// </summary>
        public static string WriteDateModified {
            get {
                return ResourceManager.GetString("WriteDateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write date taken or encoded.
        /// </summary>
        public static string WriteDateTakenOrEncoded {
            get {
                return ResourceManager.GetString("WriteDateTakenOrEncoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store video metadata as Easy metadata?.
        /// </summary>
        public static string WriteEasyMetadata {
            get {
                return ResourceManager.GetString("WriteEasyMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write GPS area information.
        /// </summary>
        public static string WriteGPSAreaInfo {
            get {
                return ResourceManager.GetString("WriteGPSAreaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write GPS coordinates.
        /// </summary>
        public static string WriteGPSCoords {
            get {
                return ResourceManager.GetString("WriteGPSCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write GPS Easy metadata.
        /// </summary>
        public static string WriteGPSEasyMetadata {
            get {
                return ResourceManager.GetString("WriteGPSEasyMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year created.
        /// </summary>
        public static string YearCreated {
            get {
                return ResourceManager.GetString("YearCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year earliest.
        /// </summary>
        public static string YearEarliest {
            get {
                return ResourceManager.GetString("YearEarliest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year from Easy metadata.
        /// </summary>
        public static string YearFromEasyMetadata {
            get {
                return ResourceManager.GetString("YearFromEasyMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year taken or encoded.
        /// </summary>
        public static string YearTakenOrEncoded {
            get {
                return ResourceManager.GetString("YearTakenOrEncoded", resourceCulture);
            }
        }
    }
}
